# Generated by Django 5.2.1 on 2025-05-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tape',
            name='date_moved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
