# Generated by Django 5.2.1 on 2025-06-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doo', '0002_tape_date_moved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediatype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='movement',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
