# Generated by Django 5.2.1 on 2025-06-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doo', '0003_alter_mediatype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='movement_date',
            field=models.DateTimeField(),
        ),
    ]
