# Generated by Django 5.2.1 on 2025-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doo', '0004_alter_movement_movement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tape',
            name='label',
            field=models.CharField(default=None, max_length=30, null=True, unique=True),
        ),
    ]
